services:
  - type: web
    name: tenis-pro-back
    env: docker
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
